[package]

name = "feed_splitter-rust"
version = "1.0.2"
authors = ["Andrii Dmytrenko <andrey@reevoo.com>"]

[dependencies.csv]
git = "git://github.com/BurntSushi/rust-csv"

[dependencies]
getopts = "*"
log = "*"
